apiVersion: v1
kind: Secret
metadata:
  name: cluster-credentials
type: Opaque
stringData:
  SECRET_KEY: "xd(marrvy5-oq7i&ihaae&p62$g+3#%$#i7$qntva70wpbl^b!"
  AUTH_SERVER: "https://db-auth.herokuapp.com/"
  cloud_name: "hawmbkjqq"
  api_key: "528453244525954"
  api_secret: "-Oy4eTG8D7W9O-r6Hnmpw9N2QWk"
